services:
  web:
      image: agendamento-servicos-web
      restart: always
      build:
        context: .
      environment:
        VITE_URL_API: http://localhost:5001/api-agenda/api/v1
        VITE_BUILD_PATH: dist
        VITE_BASE_URL: /web-agenda
      ports:
        - "5000:5000"
